name: Smoke Tests

on:
  pull_request:
    branches: [ master, main, branches/testing ]
  push:
    branches: [ master, main, branches/testing ]

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout iflow repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget unzip
        
    - name: Install Chrome and ChromeDriver (simplified)
      run: |
        # Install Chrome using apt-get (much simpler)
        sudo apt-get install -y google-chrome-stable chromium-chromedriver
        
        # Verify installations
        google-chrome --version
        chromedriver --version
        
        echo "✅ Chrome and ChromeDriver installed via apt-get"
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install radish-bdd selenium typer
        
    - name: Set up test database
      run: |
        # Checkout the test database from a predefined branch
        git clone https://github.com/iflow-dev/iflow-test-db.git .iflow-test
        cd .iflow-test
        
        # Verify the test database has the required artifacts
        if [ ! -f "artifacts/00001.yaml" ]; then
          echo "❌ Test database missing required artifact 00001.yaml"
          exit 1
        fi
        
        echo "✅ Test database setup complete"
        
    - name: Install iflow package
      run: |
        pip install -e .
        
    - name: Start iflow server
      run: |
        # Start the server in the background
        python -m iflow.web_server \
          --port 8080 \
          --database .iflow-test \
          --host 0.0.0.0 \
          --title "iflow - Test Server" &
        
        # Wait for server to start
        sleep 5
        
        # Verify server is running
        curl -f http://localhost:8080/api/project-info || exit 1
        echo "✅ iflow server started successfully"
        
    - name: Run smoke tests
      run: |
        # Set environment variable for tests
        export IFLOW_BASE_URL="http://localhost:8080"
        export PYTHONPATH="tests:$PYTHONPATH"
        
        # Run smoke tests
        echo "Running smoke tests..."
        radish -b tests tests/features/ --tags smoke
        
        echo "✅ Smoke tests completed successfully"
        
    - name: Cleanup
      if: always()
      run: |
        # Stop the server
        pkill -f "python -m iflow.web_server" || true
        echo "✅ Cleanup completed"
